### ISSUE TITLE
ucc-gen build issue with dependencies

### ISSUE THREAD

**Issue by srsplunk** [srsplunk/idelta_addon_for_google_analytics#8]
**Error generated by ucc-gen build:**

INFO: Installing os-dependentLibraries.
INFO: Executing: python3 -m pip show --version grpcio | grep "Version: 1.60.0"
ERROR: Command (python3 -m pip show --version grpcio | grep "Version: 1.60.0") returned 1 status code
ERROR: 
OS dependent library grpcio = 1.60.0 SHOULD be defined in requirements.txt.
When the os dependent library is installed without its dependencies it has to be listed in requirements.txt.
Possible solutions, either:
1. os-dependentLibraries.name[grpcio].dependencies = True
2. Add grpcio==1.60.0 in requirements.txt

Traceback (most recent call last):
  File "/Volumes/sandisk01/Dropbox/splunk_projects/google_analytics_addon/src/.venv/bin/ucc-gen", line 10, in <module>
    sys.exit(main())
  File "/Volumes/sandisk01/Dropbox/splunk_projects/google_analytics_addon/src/.venv/lib/python3.9/site-packages/splunk_add_on_ucc_framework/main.py", line 185, in main
    build.generate(
  File "/Volumes/sandisk01/Dropbox/splunk_projects/google_analytics_addon/src/.venv/lib/python3.9/site-packages/splunk_add_on_ucc_framework/commands/build.py", line 541, in generate
    install_python_libraries(
  File "/Volumes/sandisk01/Dropbox/splunk_projects/google_analytics_addon/src/.venv/lib/python3.9/site-packages/splunk_add_on_ucc_framework/install_python_libraries.py", line 121, in install_python_libraries
    cleanup_libraries = install_os_dependent_libraries(
  File "/Volumes/sandisk01/Dropbox/splunk_projects/google_analytics_addon/src/.venv/lib/python3.9/site-packages/splunk_add_on_ucc_framework/install_python_libraries.py", line 228, in install_os_dependent_libraries
    raise CouldNotInstallRequirements
splunk_add_on_ucc_framework.install_python_libraries.CouldNotInstallRequirements

**Comment by srsplunk** [comment]
added grpcio==1.60.0 to requirements.txt and build completes
